apiVersion: v1
kind: Service
metadata:
  name: postgres-checkout
  namespace: route256
  labels:
    app: postgres-checkout
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-checkout