apiVersion: v1
kind: Service
metadata:
  name: odyssey-loms
  namespace: route256
  labels:
    app: odyssey-loms
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: 6442
      targetPort: 6442
  selector:
    app: odyssey-loms