apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loms
  namespace: route256
  labels:
    name: loms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loms
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70