apiVersion: v1
kind: Service
metadata:
  name: postgres-loms
  namespace: route256
  labels:
    app: postgres-loms
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-loms