{
 "title": "Checkout",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Checkout - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"checkout:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"checkout:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"checkout:8080\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"checkout\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout - RPS across handlers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(route256_grpc_server_requests_total{job=\"checkout\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_postgres_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_postgres_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_postgres_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Postgres - DB operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(route256_postgres_requests_total{job=\"checkout\", operation=\"query\"}[1m]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(rate(route256_postgres_requests_total{job=\"checkout\", operation=\"exec\"}[1m]))",
     "legendFormat": "Execs"
    }
   ]
  },
  {
   "title": "Postgres - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{job=\"checkout\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "/AddToCart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "AddToCart - RPC by response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(route256_grpc_server_responses_total{job=\"checkout\", method=\"/checkout.Checkout/AddToCart\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AddToCart - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/AddToCart\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/AddToCart\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/AddToCart\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "/DeleteFromCart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "DeleteFromCart - RPC by response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(route256_grpc_server_responses_total{job=\"checkout\", method=\"/checkout.Checkout/DeleteFromCart\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DeleteFromCart - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{job=\"checkout\", method=\"/checkout.Checkout/DeleteFromCart\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/DeleteFromCart\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/DeleteFromCart\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "/ListCart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "ListCart - RPC by response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(route256_grpc_server_responses_total{method=\"/checkout.Checkout/ListCart\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ListCart - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/ListCart\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/ListCart\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/ListCart\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "/Purchase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  },
  {
   "title": "Purchase - RPC by response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(route256_grpc_server_responses_total{job=\"checkout\", method=\"/checkout.Checkout/Purchase\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchase - Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/Purchase\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/Purchase\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(route256_grpc_server_histogram_response_time_seconds_bucket{method=\"/checkout.Checkout/Purchase\"}[1m])))",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}