route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '5817670751:AAFQqo56DDFxcJ7bOpxzvQbZ1MNFzyDxjY4'
        api_url: 'https://api.telegram.org'
        chat_id: 417523632
        message: "⚠️*{{ .GroupLabels.alertname }}*⚠️\nSeverity: *{{ .CommonLabels.severity }}*\n{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        parse_mode: 'Markdown'
