version: "3.9"

networks:
  route256:
    name: "route256_route256"
    external: true

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - route256
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    networks:
      - route256
    ports:
      - "9089:9089"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=:9089'

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    networks:
      - route256
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    links:
      - prometheus
